### PR TITLE
View my offers

### LINKED ISSUE #14: View My Offers - API
- Validate that the user is auth and verified.
- Get all offers for the logged-in user with its status, total price and the accepted baby sitter.

### PR DESCRIPTION
**Pull request by mnourrhan**
- create API for retrieving the logged-in user offers.
- add test cases for testing the created API.

### CODE REVIEW

**Review by AbdullahMuhammed5 — DISMISSED** [review]

**Review by aminetiyal — APPROVED** [review]

**Review by RanaEmad — APPROVED** [review]

**Comment by RanaEmad** [comment]
@mnourrhan just resolve the conflicts to get it merged

**Comment by mnourrhan** [comment]
@RanaEmad Solved!

**Comment by RanaEmad** [comment]
> @RanaEmad Solved!

Once I merged your other PR other conflicts showed @mnourrhan :(

**Comment by mnourrhan** [comment]
> > @RanaEmad Solved!
> 
> Once I merged your other PR other conflicts showed @mnourrhan :(

No problem, I expect that :)
Solved now

**Pull request merged**
