### PR TITLE
Reset password

### LINKED ISSUE #6: Reset Password - API
- Validate that reset password token is not expired
- Reset user password.
- Login user and return auth token with a success message.
- If the user not verified, return an error message.

### PR DESCRIPTION
**Pull request by mnourrhan**
Create reset password API.

### CODE REVIEW

**Review by AbdullahMuhammed5 — DISMISSED** [review]

**Review by aminetiyal — DISMISSED** [review]

**Comment by RanaEmad** [comment]
Please, resolve the conflicts so that I could merge this PR @mnourrhan

**Comment by mnourrhan** [comment]
> Please, resolve the conflicts so that I could merge this PR @mnourrhan

Done

**Review by AbdullahMuhammed5 — APPROVED** [review]

**Review by RanaEmad — APPROVED** [review]

**Comment by RanaEmad** [comment]
@mnourrhan just resolve the conflicts to get it merged

**Comment by mnourrhan** [comment]
@RanaEmad Solved!

**Pull request merged**
